/**
 * T4 tests: RFC 6962 Merkle transparency log.
 * Run compiled: node --test dist/test/merkle.test.js
 *
 * Part 1 — cross-language conformance against
 * packages/vectors/merkle-vectors.json (generated by generate-merkle.py,
 * which exhaustively self-checks with Python hashlib before writing).
 * Part 2 — unit/behavior tests of the MerkleLog API.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import {
  MerkleLog,
  verifyInclusionProof,
  verifyConsistencyProof,
  leafHash,
  nodeHash,
  toHex,
  fromHex,
} from "../src/index.js";
// See src/tree.ts note on this deep relative import.
import { canonicalizeBytes } from "@veritas/attestation-core";

const here = dirname(fileURLToPath(import.meta.url));
const vectors = JSON.parse(
  readFileSync(join(here, "..", "..", "..", "vectors", "merkle-vectors.json"), "utf-8"),
);

const leafBytes: Uint8Array[] = vectors.leaves_hex.map((h: string) => fromHex(h));

function buildLog(n: number): MerkleLog {
  const log = new MerkleLog();
  for (let i = 0; i < n; i++) log.append(leafBytes[i % leafBytes.length]);
  return log;
}

/** Independent naive RFC 6962 root (written separately from src/tree.ts). */
function naiveRoot(leaves: Uint8Array[]): Uint8Array {
  const rec = (ls: Uint8Array[]): Uint8Array => {
    if (ls.length === 1) return leafHash(ls[0]);
    let k = 1;
    while (k * 2 < ls.length) k *= 2;
    return nodeHash(rec(ls.slice(0, k)), rec(ls.slice(k)));
  };
  return rec(leaves);
}

// ---------------------------------------------------------------------------
// Part 1 — cross-language vectors
// ---------------------------------------------------------------------------

for (const r of vectors.roots) {
  test(`vectors/root n=${r.n} byte-identical`, () => {
    assert.equal(buildLog(r.n).getRoot(), r.root);
  });
}

for (const p of vectors.inclusion_proofs) {
  test(`vectors/inclusion n=${p.n} index=${p.index} byte-identical`, () => {
    const proof = buildLog(p.n).getProof(p.index);
    assert.deepEqual(proof, {
      leaf: p.leaf,
      index: p.index,
      size: p.n,
      path: p.path,
      root: p.root,
    });
  });

  test(`vectors/inclusion n=${p.n} index=${p.index} verifies`, () => {
    assert.equal(
      verifyInclusionProof({
        leaf: p.leaf,
        index: p.index,
        size: p.n,
        path: p.path,
        root: p.root,
      }),
      true,
    );
  });

  test(`vectors/inclusion n=${p.n} index=${p.index} rejects tampered sibling`, () => {
    const bad = {
      leaf: p.leaf,
      index: p.index,
      size: p.n,
      path: p.path.map((s: { hash: string; left: boolean }, i: number) =>
        i === 0
          ? { hash: s.hash.slice(0, -1) + (s.hash.endsWith("0") ? "1" : "0"), left: s.left }
          : s,
      ),
      root: p.root,
    };
    assert.equal(verifyInclusionProof(bad), false);
  });
}

for (const c of vectors.consistency_proofs) {
  test(`vectors/consistency m=${c.old_size} n=${c.new_size} byte-identical`, () => {
    const proof = buildLog(c.new_size).getConsistencyProof(c.old_size, c.new_size);
    assert.deepEqual(proof, {
      oldSize: c.old_size,
      newSize: c.new_size,
      oldRoot: c.old_root,
      newRoot: c.new_root,
      blocks: c.blocks,
    });
  });

  test(`vectors/consistency m=${c.old_size} n=${c.new_size} verifies`, () => {
    assert.equal(
      verifyConsistencyProof({
        oldSize: c.old_size,
        newSize: c.new_size,
        oldRoot: c.old_root,
        newRoot: c.new_root,
        blocks: c.blocks,
      }),
      true,
    );
  });

  test(`vectors/consistency m=${c.old_size} n=${c.new_size} rejects forged old root`, () => {
    assert.equal(
      verifyConsistencyProof({
        oldSize: c.old_size,
        newSize: c.new_size,
        oldRoot: "00".repeat(32),
        newRoot: c.new_root,
        blocks: c.blocks,
      }),
      false,
    );
  });
}

// ---------------------------------------------------------------------------
// Part 2 — behavior
// ---------------------------------------------------------------------------

test("append returns sequential indices and evolving roots", () => {
  const log = new MerkleLog();
  const r0 = log.append(new Uint8Array([1]));
  const r1 = log.append(new Uint8Array([2]));
  assert.equal(r0.index, 0);
  assert.equal(r1.index, 1);
  assert.notEqual(r0.root, r1.root);
  assert.equal(log.size, 2);
});

for (let n = 1; n <= 40; n++) {
  test(`round-trip n=${n}: every inclusion proof verifies, root matches naive`, () => {
    const leaves = Array.from({ length: n }, (_, i) =>
      new TextEncoder().encode(`leaf-${i}`),
    );
    const log = new MerkleLog();
    for (const l of leaves) log.append(l);
    assert.equal(toHex(naiveRoot(leaves)), log.getRoot());
    for (let i = 0; i < n; i++) {
      const proof = log.getProof(i);
      assert.equal(proof.size, n);
      assert.equal(verifyInclusionProof(proof), true);
    }
  });
}

test("consistency round-trip across assorted (m,n)", () => {
  const log = buildLog(24);
  const pairs: Array<[number, number]> = [
    [1, 1],
    [1, 24],
    [24, 24],
    [7, 8],
    [8, 9],
    [3, 17],
    [15, 16],
    [16, 17],
    [12, 24],
  ];
  for (const [m, n] of pairs) {
    const proof = log.getConsistencyProof(m, n);
    assert.equal(verifyConsistencyProof(proof), true);
    // oldRoot must equal the root of a standalone size-m tree
    assert.equal(proof.oldRoot, buildLog(m).getRoot());
    assert.equal(proof.newRoot, buildLog(n).getRoot());
  }
});

test("verifyInclusionProof rejects garbage", () => {
  assert.equal(verifyInclusionProof(null as never), false);
  assert.equal(
    verifyInclusionProof({
      leaf: "zz",
      index: 0,
      size: 1,
      path: [],
      root: "00".repeat(32),
    }),
    false,
  );
  const log = buildLog(4);
  const p = log.getProof(0);
  // Note: the index field is metadata, not cryptographically bound — the proof
  // attests that *this leaf* is in the tree, whatever index is claimed.
  assert.equal(verifyInclusionProof({ ...p, index: 3 }), true);
  assert.equal(verifyInclusionProof({ ...p, root: "ff".repeat(32) }), false);
  assert.equal(
    verifyInclusionProof({ ...p, leaf: Buffer.from("forged").toString("hex") }),
    false,
  );
});

test("journal persistence: reload reproduces root and proofs", () => {
  const dir = mkdtempSync(join(tmpdir(), "veritas-log-"));
  try {
    const journal = join(dir, "log.jsonl");
    const log = new MerkleLog(journal);
    for (let i = 0; i < 50; i++) log.append(new TextEncoder().encode(`j-${i}`));
    const root = log.getRoot();

    const again = MerkleLog.load(journal);
    assert.equal(again.size, 50);
    assert.equal(again.getRoot(), root);
    for (const i of [0, 7, 49]) {
      assert.equal(verifyInclusionProof(again.getProof(i)), true);
    }
    // Appending after load continues the journal.
    const r = again.append(new TextEncoder().encode("j-50"));
    assert.equal(r.index, 50);
    const third = MerkleLog.load(journal);
    assert.equal(third.size, 51);
    assert.equal(third.getRoot(), again.getRoot());
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("audit script replays a journal and matches the published root", async () => {
  const dir = mkdtempSync(join(tmpdir(), "veritas-audit-"));
  try {
    const journal = join(dir, "log.jsonl");
    const log = new MerkleLog(journal);
    for (let i = 0; i < 37; i++) log.appendAttestation({ seq: i });
    const root = log.getRoot();

    const { execFileSync } = await import("node:child_process");
    const script = join(here, "..", "scripts", "audit-log.js");
    const out = execFileSync("node", [script, journal, root], { encoding: "utf-8" });
    assert.match(out, /OK: recomputed root matches expected root/);

    // Wrong expected root -> exit 1.
    assert.throws(() =>
      execFileSync("node", [script, journal, "00".repeat(32)], { stdio: "pipe" }),
    );
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("appendAttestation canonicalizes with the T1 reference lib", () => {
  const log = new MerkleLog();
  const obj = { b: 1, a: [3, 2, 1] };
  const { index } = log.appendAttestation(obj);
  const proof = log.getProof(index);
  assert.equal(proof.leaf, Buffer.from(canonicalizeBytes(obj)).toString("hex"));
  assert.equal(verifyInclusionProof(proof), true);
});

test("empty log and bad arguments throw", () => {
  const log = new MerkleLog();
  assert.throws(() => log.getRoot(), /empty/);
  assert.throws(() => log.getProof(0), /out of range/);
  log.append(new Uint8Array([9]));
  assert.throws(() => log.getProof(-1), /out of range/);
  assert.throws(() => log.getProof(1), /out of range/);
  assert.throws(() => log.getConsistencyProof(0, 1), /1 <= oldSize/);
  assert.throws(() => log.getConsistencyProof(2, 1), /1 <= oldSize/);
  assert.throws(() => log.getConsistencyProof(1, 2), /1 <= oldSize/);
  assert.equal(verifyConsistencyProof({ ...log.getConsistencyProof(1, 1), newSize: 2 }), false);
});
